## **1) Knihovny a moduly pro matematické výpočty**

### **Skalární součin**

#### Python

In [513]:
import numpy as np
import time

a = [25, 45, 14, 35, 2, 6, 34]
b = [36, 86, 93, 11, 26, 57, 78]

t = time.perf_counter()

def dot_product(a, b): 
    val = 0
    for i, j in zip(a, b):
        val += i * j
    return val
print(f"Výsledek: {dot_product(a, b)}\nČas: {time.perf_counter() - t}s") 

Výsledek: 9503
Čas: 5.630000000422797e-05s


#### NumPy

In [514]:
a = np.array([25, 45, 14, 35, 2, 6, 34])
b = np.array([36, 86, 93, 11, 26, 57, 78])

t = time.perf_counter()

print(f"Výsledek: {a @ b}\nČas: {time.perf_counter() - t}s")

Výsledek: 9503
Čas: 3.749999999769216e-05s


### **Určitý integrál**

#### Python

In [515]:
# Pomocí Newtonových-Cotesových vzorců

def f(x): 
    return (x**2 - 30) / (x + 2)
   
a = 5
b = 10
dx = 0.001

t = time.perf_counter()

n = int((b - a) // dx) + 1
integral = f(a) + f(b)

for i in range(1, n):
    integral += 2 * f(a + i * dx)

integral *= dx / 2

print(f"Výsledek: {integral}\nČas: {time.perf_counter() - t}s")

Výsledek: 13.486090951778758
Čas: 0.0016778999999971234s


#### SciPy

In [516]:
import scipy.integrate as integrate

def f(x): 
    return (x**2 - 30) / (x + 2)

t = time.perf_counter()
res = integrate.quad(f, a, b)

print(f"Výsledek: {res[0]}\nČas: {time.perf_counter() - t}s")

Výsledek: 13.486090980950138
Čas: 5.8099999996841234e-05s


### **Výpočet determinantu**

#### Python

In [517]:
def determinant(matrix, mul=1):
    width = len(matrix)
    if width == 1:
        return mul * matrix[0][0]
    else:
        sign = -1
        answer = 0
        for i in range(width):
            m = []
            for j in range(1, width):
                buff = []
                for k in range(width):
                    if k != i:
                        buff.append(matrix[j][k])
                m.append(buff)
            sign *= -1
            answer = answer + mul * determinant(m, sign * matrix[0][i])
    return answer

a = [[5, 3, 7, 7], [8, 10, 2, 6], [1, 4, 4, 2], [5, 8, 5, 7]]
t = time.perf_counter()

print(f"Výsledek: {determinant(a)}\nČas: {time.perf_counter() - t}s")

Výsledek: 408
Čas: 6.0400000002402976e-05s


#### NumPy

In [518]:
a = np.array([[5, 3, 7, 7], [8, 10, 2, 6], [1, 4, 4, 2], [5, 8, 5, 7]])
val = np.linalg.det(a)
t = time.perf_counter()

print(f"Výsledek: {val}\nČas: {time.perf_counter() - t}s")

Výsledek: 407.9999999999999
Čas: 2.5700000001904755e-05s


### **Transpozice matic**

#### Python

In [519]:
def transpose(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    matrix_n = []

    for j in range(cols):
        row = []
        for i in range(rows):
           row.append(matrix[i][j])
        matrix_n.append(row)

    return matrix_n

a = [[7, 8, 9, 7], [4, 6, 7, 6], [8, 5, 3, 1]]
t = time.perf_counter()

print(f"Výsledek:\n{transpose(a)}\nČas: {time.perf_counter() - t}s")

Výsledek:
[[7, 4, 8], [8, 6, 5], [9, 7, 3], [7, 6, 1]]
Čas: 2.83000000038669e-05s


#### NumPy

In [520]:
a = np.array([[7, 8, 9, 7], [4, 6, 7, 6], [8, 5, 3, 1]])
t = time.perf_counter()

print(f"Výsledek:\n{a.transpose()}\nČas: {time.perf_counter() - t}s")

Výsledek:
[[7 4 8]
 [8 6 5]
 [9 7 3]
 [7 6 1]]
Čas: 0.00012080000000480595s


### **Kvadratické rovnice**

#### **Rovnice: x^2 + 4x - 20 = 0**

#### Python

In [521]:
import cmath

def quadratic_equation(a, b, c):
    D = (b ** 2) - (4 * a * c)
    first_root = (-b - cmath.sqrt(D)) / (2 * a)
    second_root = (-b + cmath.sqrt(D)) / (2 * a)
    return [first_root, second_root]

t = time.perf_counter()

print(f"Výsledek:{quadratic_equation(1, 4, -20)}\nČas: {time.perf_counter() - t}s")

Výsledek:[(-6.898979485566356+0j), (2.8989794855663558+0j)]
Čas: 3.480000000166683e-05s


#### NumPy

In [522]:
coeff = [1, 4, -20]
t = time.perf_counter()
sol = np.roots(coeff)

print(f"Výsledek: {sol}\nČas: {time.perf_counter() - t}s")

Výsledek: [-6.89897949  2.89897949]
Čas: 0.00033100000000274576s
